name: network_analysis
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - ca-certificates=2021.10.8=h5b45459_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - debugpy=1.5.1=py38h885f38d_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - ipykernel=6.5.0=py38h595d716_1
  - ipython=7.30.0=py38haa244fe_0
  - jedi=0.18.1=py38haa244fe_0
  - jupyter_client=7.1.0=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py38haa244fe_1
  - libsodium=1.0.18=h8d14728_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - openssl=3.0.0=h8ffe710_2
  - parso=0.8.2=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=21.3.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.22=pyha770c72_0
  - pygments=2.10.0=pyhd8ed1ab_0
  - python=3.8.12=h900ac77_2_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pywin32=302=py38h294d835_2
  - pyzmq=22.3.0=py38h09162b1_1
  - setuptools=59.4.0=py38haa244fe_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.0=h8ffe710_0
  - tornado=6.1=py38h294d835_2
  - traitlets=5.1.1=pyhd8ed1ab_0
  - ucrt=10.0.20348.0=h57928b3_0
  - vc=14.2=hb210afc_5
  - vs2015_runtime=14.29.30037=h902a5da_5
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.0=pyhd8ed1ab_1
  - zeromq=4.3.4=h0e60522_1
  - pip:
    - certifi==2021.10.8
    - charset-normalizer==2.0.8
    - cycler==0.11.0
    - cython==0.29.23
    - fonttools==4.28.2
    - idna==3.3
    - igraph==0.9.8
    - joblib==1.1.0
    - kiwisolver==1.3.2
    - leidenalg==0.8.8
    - matplotlib==3.5.0
    - networkx==2.6.3
    - numpy==1.21.4
    - packaging==21.3
    - pandas==1.3.4
    - pillow==8.4.0
    - plotly==5.4.0
    - pyparsing==3.0.6
    - python-igraph==0.9.8
    - python-louvain==0.15
    - pytz==2021.3
    - requests==2.26.0
    - scikit-learn==1.0.1
    - scipy==1.7.3
    - setuptools-scm==6.3.2
    - smart-open==5.2.1
    - tenacity==8.0.1
    - texttable==1.6.4
    - threadpoolctl==3.0.0
    - tomli==1.2.2
    - tqdm==4.62.3
    - urllib3==1.26.7
prefix: D:\Anaconda3\envs\network_analysis
